gen_bases = [
	{"name": "+#% Monster Chaos Resistance", "strs": ['+', '% Monster Chaos Resistance']},
	{"name": "+#% Monster Elemental Resistance", "strs": ['+', '% Monster Elemental Resistance']},
	{"name": "+#% Monster Physical Damage Reduction", "strs": ['+', '% Monster Physical Damage Reduction']},
	{"name": "All Monster Damage from Hits always Ignites", "strs": ['All Monster Damage from Hits always Ignites']},
	{"name": "Area contains many Totems", "strs": ['Area contains many Totems']},
	{"name": "Area contains two Unique Bosses", "strs": ['Area contains two Unique Bosses']},
	{"name": "Area has increased monster variety", "strs": ['Area has increased monster variety']},
	{"name": "Area has patches of Burning Ground", "strs": ['Area has patches of Burning Ground']},
	{"name": "Area has patches of Chilled Ground", "strs": ['Area has patches of Chilled Ground']},
	{"name": "Area has patches of Shocked Ground which increase Damage taken by #%", "strs": ['Area has patches of Shocked Ground which increase Damage taken by', '%']},
	{"name": "Area has patches of desecrated ground", "strs": ['Area has patches of desecrated ground']},
	{"name": "Area is inhabited by Abominations", "strs": ['Area is inhabited by Abominations']},
	{"name": "Area is inhabited by Animals", "strs": ['Area is inhabited by Animals']},
	{"name": "Area is inhabited by Cultists of Kitava", "strs": ['Area is inhabited by Cultists of Kitava']},
	{"name": "Area is inhabited by Demons", "strs": ['Area is inhabited by Demons']},
	{"name": "Area is inhabited by Ghosts", "strs": ['Area is inhabited by Ghosts']},
	{"name": "Area is inhabited by Goatmen", "strs": ['Area is inhabited by Goatmen']},
	{"name": "Area is inhabited by Humanoids", "strs": ['Area is inhabited by Humanoids']},
	{"name": "Area is inhabited by Lunaris fanatics", "strs": ['Area is inhabited by Lunaris fanatics']},
	{"name": "Area is inhabited by Sea Witches and their Spawn", "strs": ['Area is inhabited by Sea Witches and their Spawn']},
	{"name": "Area is inhabited by Skeletons", "strs": ['Area is inhabited by Skeletons']},
	{"name": "Area is inhabited by Solaris fanatics", "strs": ['Area is inhabited by Solaris fanatics']},
	{"name": "Area is inhabited by Undead", "strs": ['Area is inhabited by Undead']},
	{"name": "Area is inhabited by ranged monsters", "strs": ['Area is inhabited by ranged monsters']},
	{"name": "Area is inhabited by # additional Rogue Exile", "strs": ['Area is inhabited by', 'additional Rogue Exile']},
	{"name": "Area is inhabited by # additional Rogue Exiles", "strs": ['Area is inhabited by', 'additional Rogue Exiles']},
	{"name": "Cannot Leech from Monsters", "strs": ['Cannot Leech from Monsters']},
	{"name": "Magic Monster Packs each have a Bloodline Mod", "strs": ['Magic Monster Packs each have a Bloodline Mod']},
	{"name": "Monsters Poison on Hit", "strs": ['Monsters Poison on Hit']},
	{"name": "Monsters are Hexproof", "strs": ['Monsters are Hexproof']},
	{"name": "Monsters cannot be Stunned", "strs": ['Monsters cannot be Stunned']},
	{"name": "Monsters cannot be Taunted", "strs": ['Monsters cannot be Taunted']},
	{"name": "Monsters cannot be affected by Elemental Ailments", "strs": ['Monsters cannot be affected by Elemental Ailments']},
	{"name": "Monsters deal #% extra Physical Damage as Cold", "strs": ['Monsters deal', '% extra Physical Damage as Cold']},
	{"name": "Monsters deal #% extra Physical Damage as Fire", "strs": ['Monsters deal', '% extra Physical Damage as Fire']},
	{"name": "Monsters deal #% extra Physical Damage as Lightning", "strs": ['Monsters deal', '% extra Physical Damage as Lightning']},
	{"name": "Monsters fire # additional Projectiles", "strs": ['Monsters fire', 'additional Projectiles']},
	{"name": "Monsters gain a Frenzy Charge on Hit", "strs": ['Monsters gain a Frenzy Charge on Hit']},
	{"name": "Monsters gain a Power Charge on Hit", "strs": ['Monsters gain a Power Charge on Hit']},
	{"name": "Monsters gain an Endurance Charge on Hit", "strs": ['Monsters gain an Endurance Charge on Hit']},
	{"name": "Monsters have a #% chance to avoid Poison, Blind, and Bleeding", "strs": ['Monsters have a', '% chance to avoid Poison, Blind, and Bleeding']},
	{"name": "Monsters have a #% chance to cause Elemental Ailments on Hit", "strs": ['Monsters have a', '% chance to cause Elemental Ailments on Hit']},
	{"name": "Monsters have #% chance to Avoid Elemental Ailments", "strs": ['Monsters have', '% chance to Avoid Elemental Ailments']},
	{"name": "Monsters have #% chance to gain a Frenzy Charge on Hit", "strs": ['Monsters have', '% chance to gain a Frenzy Charge on Hit']},
	{"name": "Monsters have #% chance to gain a Power Charge on Hit", "strs": ['Monsters have', '% chance to gain a Power Charge on Hit']},
	{"name": "Monsters have #% chance to gain an Endurance Charge on Hit", "strs": ['Monsters have', '% chance to gain an Endurance Charge on Hit']},
	{"name": "Monsters have #% increased Accuracy Rating", "strs": ['Monsters have', '% increased Accuracy Rating']},
	{"name": "Monsters have #% increased Area of Effect", "strs": ['Monsters have', '% increased Area of Effect']},
	{"name": "Monsters have #% increased Critical Strike Chance", "strs": ['Monsters have', '% increased Critical Strike Chance']},
	{"name": "Monsters reflect #% of Elemental Damage", "strs": ['Monsters reflect', '% of Elemental Damage']},
	{"name": "Monsters reflect #% of Physical Damage", "strs": ['Monsters reflect', '% of Physical Damage']},
	{"name": "Monsters take #% reduced Extra Damage from Critical Strikes", "strs": ['Monsters take', '% reduced Extra Damage from Critical Strikes']},
	{"name": "Monsters' Action Speed cannot be modified to below base value", "strs": ["Monsters' Action Speed cannot be modified to below base value"]},
	{"name": "Monsters' skills Chain # additional times", "strs": ["Monsters' skills Chain", 'additional times']},
	{"name": "Players and Monsters fire # additional Projectiles", "strs": ['Players and Monsters fire', 'additional Projectiles']},
	{"name": "Players are Cursed with Elemental Weakness", "strs": ['Players are Cursed with Elemental Weakness']},
	{"name": "Players are Cursed with Enfeeble", "strs": ['Players are Cursed with Enfeeble']},
	{"name": "Players are Cursed with Temporal Chains", "strs": ['Players are Cursed with Temporal Chains']},
	{"name": "Players are Cursed with Vulnerability", "strs": ['Players are Cursed with Vulnerability']},
	{"name": "Players cannot Regenerate Life, Mana or Energy Shield", "strs": ['Players cannot Regenerate Life, Mana or Energy Shield']},
	{"name": "Players cannot inflict Exposure", "strs": ['Players cannot inflict Exposure']},
	{"name": "Players gain #% reduced Flask Charges", "strs": ['Players gain', '% reduced Flask Charges']},
	{"name": "Players have Point Blank", "strs": ['Players have Point Blank']},
	{"name": "Players have #% less Area of Effect", "strs": ['Players have', '% less Area of Effect']},
	{"name": "Players have #% less Armour", "strs": ['Players have', '% less Armour']},
	{"name": "Players have #% less Recovery Rate of Life and Energy Shield", "strs": ['Players have', '% less Recovery Rate of Life and Energy Shield']},
	{"name": "Players have #% reduced Chance to Block", "strs": ['Players have', '% reduced Chance to Block']},
	{"name": "Players have #% to amount of Suppressed Spell Damage Prevented", "strs": ['Players have', '% to amount of Suppressed Spell Damage Prevented']},
	{"name": "Rare Monsters each have a Nemesis Mod", "strs": ['Rare Monsters each have a Nemesis Mod']},
	{"name": "Slaying Enemies close together attracts monsters from Beyond", "strs": ['Slaying Enemies close together attracts monsters from Beyond']},
	{"name": "Slaying Enemies close together has a #% chance to attract monsters from Beyond", "strs": ['Slaying Enemies close together has a', '% chance to attract monsters from Beyond']},
	{"name": "Unique Boss deals #% increased Damage", "strs": ['Unique Boss deals', '% increased Damage']},
	{"name": "Unique Boss has #% increased Area of Effect", "strs": ['Unique Boss has', '% increased Area of Effect']},
	{"name": "Unique Boss has #% increased Attack and Cast Speed", "strs": ['Unique Boss has', '% increased Attack and Cast Speed']},
	{"name": "Unique Boss has #% increased Life", "strs": ['Unique Boss has', '% increased Life']},
	{"name": "#% increased Monster Attack Speed", "strs": ['', '% increased Monster Attack Speed']},
	{"name": "#% increased Monster Cast Speed", "strs": ['', '% increased Monster Cast Speed']},
	{"name": "#% increased Monster Damage", "strs": ['', '% increased Monster Damage']},
	{"name": "#% increased Monster Movement Speed", "strs": ['', '% increased Monster Movement Speed']},
	{"name": "#% less effect of Curses on Monsters", "strs": ['', '% less effect of Curses on Monsters']},
	{"name": "#% maximum Player Resistances", "strs": ['', '% maximum Player Resistances']},
	{"name": "#% more Magic Monsters", "strs": ['', '% more Magic Monsters']},
	{"name": "#% more Monster Life", "strs": ['', '% more Monster Life']},
	{"name": "#% more Rare Monsters", "strs": ['', '% more Rare Monsters']}
]