gen_bases = [
	{"name": "Unique Boss has #% increased Area of Effect", "strs": ['Unique Boss has', '% increased Area of Effect']},
	{"name": "Area has patches of Chilled Ground", "strs": ['Area has patches of Chilled Ground']},
	{"name": "Cannot Leech Life from Monsters", "strs": ['Cannot Leech Life from Monsters']},
	{"name": "Players are Cursed with Enfeeble", "strs": ['Players are Cursed with Enfeeble']},
	{"name": "Monsters have a #% chance to cause Elemental Ailments on Hit", "strs": ['Monsters have a', '% chance to cause Elemental Ailments on Hit']},
	{"name": "Monsters take #% reduced Extra Damage from Critical Strikes", "strs": ['Monsters take', '% reduced Extra Damage from Critical Strikes']},
	{"name": "Monsters have #% chance to Avoid Elemental Ailments", "strs": ['Monsters have', '% chance to Avoid Elemental Ailments']},
	{"name": "#% increased Monster Damage", "strs": ['', '% increased Monster Damage']},
	{"name": "#% increased Monster Movement Speed", "strs": ['', '% increased Monster Movement Speed']},
	{"name": "Monsters have #% increased Area of Effect", "strs": ['Monsters have', '% increased Area of Effect']},
	{"name": "+#% Monster Physical Damage Reduction", "strs": ['+', '% Monster Physical Damage Reduction']},
	{"name": "Monsters cannot be affected by Elemental Ailments", "strs": ['Monsters cannot be affected by Elemental Ailments']},
	{"name": "Monsters reflect #% of Physical Damage", "strs": ['Monsters reflect', '% of Physical Damage']},
	{"name": "Area has patches of Shocked Ground which increase Damage taken by #%", "strs": ['Area has patches of Shocked Ground which increase Damage taken by', '%']},
	{"name": "#% increased Monster Attack Speed", "strs": ['', '% increased Monster Attack Speed']},
	{"name": "Players are Cursed with Temporal Chains", "strs": ['Players are Cursed with Temporal Chains']},
	{"name": "#% more Monster Life", "strs": ['', '% more Monster Life']},
	{"name": "Area has patches of desecrated ground", "strs": ['Area has patches of desecrated ground']},
	{"name": "+#% Monster Elemental Resistance", "strs": ['+', '% Monster Elemental Resistance']},
	{"name": "#% maximum Player Resistances", "strs": ['', '% maximum Player Resistances']},
	{"name": "Unique Boss has #% increased Attack and Cast Speed", "strs": ['Unique Boss has', '% increased Attack and Cast Speed']},
	{"name": "Players have #% less Area of Effect", "strs": ['Players have', '% less Area of Effect']},
	{"name": "Monsters have a #% chance to avoid Poison, Blind, and Bleeding", "strs": ['Monsters have a', '% chance to avoid Poison, Blind, and Bleeding']},
	{"name": "Players have #% reduced Chance to Block", "strs": ['Players have', '% reduced Chance to Block']},
	{"name": "#% less effect of Curses on Monsters", "strs": ['', '% less effect of Curses on Monsters']},
	{"name": "+#% Monster Chaos Resistance", "strs": ['+', '% Monster Chaos Resistance']},
	{"name": "Monsters cannot be Stunned", "strs": ['Monsters cannot be Stunned']},
	{"name": "Players have #% less Recovery Rate of Life and Energy Shield", "strs": ['Players have', '% less Recovery Rate of Life and Energy Shield']},
	{"name": "Monsters have #% reduced Accuracy Rating", "strs": ['Monsters have', '% reduced Accuracy Rating']},
	{"name": "Unique Boss has #% increased Life", "strs": ['Unique Boss has', '% increased Life']},
	{"name": "Cannot Leech Mana from Monsters", "strs": ['Cannot Leech Mana from Monsters']},
	{"name": "Players gain #% reduced Flask Charges", "strs": ['Players gain', '% reduced Flask Charges']},
	{"name": "Players have #% less Armour", "strs": ['Players have', '% less Armour']},
	{"name": "Monsters have #% reduced Area of Effect", "strs": ['Monsters have', '% reduced Area of Effect']},
	{"name": "Player chance to Dodge is Unlucky", "strs": ['Player chance to Dodge is Unlucky']},
	{"name": "Monsters have #% increased Critical Strike Chance", "strs": ['Monsters have', '% increased Critical Strike Chance']},
	{"name": "Area has patches of Burning Ground", "strs": ['Area has patches of Burning Ground']},
	{"name": "Monsters deal #% extra Physical Damage as Cold", "strs": ['Monsters deal', '% extra Physical Damage as Cold']},
	{"name": "Monsters deal #% extra Physical Damage as Fire", "strs": ['Monsters deal', '% extra Physical Damage as Fire']},
	{"name": "Monsters are Hexproof", "strs": ['Monsters are Hexproof']},
	{"name": "Unique Boss deals #% increased Damage", "strs": ['Unique Boss deals', '% increased Damage']},
	{"name": "Monsters reflect #% of Elemental Damage", "strs": ['Monsters reflect', '% of Elemental Damage']},
	{"name": "Monsters take #% increased Extra Damage from Critical Strikes", "strs": ['Monsters take', '% increased Extra Damage from Critical Strikes']},
	{"name": "Players are Cursed with Vulnerability", "strs": ['Players are Cursed with Vulnerability']},
	{"name": "Players are Cursed with Elemental Weakness", "strs": ['Players are Cursed with Elemental Weakness']},
	{"name": "Monsters deal #% extra Physical Damage as Lightning", "strs": ['Monsters deal', '% extra Physical Damage as Lightning']},
	{"name": "#% increased Monster Cast Speed", "strs": ['', '% increased Monster Cast Speed']},
	{"name": "Monsters have #% increased Accuracy Rating", "strs": ['Monsters have', '% increased Accuracy Rating']},
	{"name": "Monsters have #% reduced Critical Strike Chance", "strs": ['Monsters have', '% reduced Critical Strike Chance']},
	{"name": "Players cannot Regenerate Life, Mana or Energy Shield", "strs": ['Players cannot Regenerate Life, Mana or Energy Shield']}
]