subnames = {
	"monsters fire # additional projectiles": ['players and monsters fire # additional projectiles'],
	"area is inhabited by # additional rogue exile": ['area is inhabited by # additional rogue exiles'],
}

ngrams = {
	"#% increased monster attack speed": {"%", "% i", "% increased m", "ack", "ase", "ased", "att", "cre", "d mo", "ed mo", "eed", "k s", "mon", "nst", "pee", "r a", "rea", "sed m", "spe", "tac"},
	"#% increased monster cast speed": {"%", "% i", "% increased m", "ase", "ased", "cre", "d mo", "ed mo", "eed", "mon", "nst", "pee", "r c", "r ca", "rea", "sed m", "spe", "st s", "t spe", "ter c"},
	"#% increased monster damage": {"%", "% i", "% increased m", "ama", "ase", "ased", "cre", "d mo", "d monster d", "ed mo", "mon", "nst", "r d", "rea", "sed m"},
	"#% increased monster movement speed": {"%", "% i", "% increased m", "ase", "ased", "cre", "d mo", "ed mo", "eed", "emen", "mon", "mov", "nst", "pee", "rea", "sed m", "spe", "t spe"},
	"#% less effect of curses on monsters": {"%", "% l", "ect", "eff", "es o", "ess", "f c", "ff", "les", "mon", "n m", "nst", "s o", "s on", "ses", "ters"},
	"#% maximum player resistances": {"%", "% m", "ance", "ax", "ist", "lay", "sis", "tan", "ye"},
	"#% more magic monsters": {"%", "% m", "% mo", "e ma", "gi", "mon", "more", "nst", "ore m", "re m", "ters"},
	"#% more monster life": {"%", "% m", "% mo", "e mo", "e mon", "if", "ife", "mon", "more", "nst", "ore m", "r li", "re m"},
	"#% more rare monsters": {"%", "% m", "% mo", "e mo", "e mon", "e ra", "mon", "more", "nst", "rar", "re m", "ters"},
	"+#% monster chaos resistance": {"%", "% m", "% mo", "+", "ance", "ao", "ist", "mon", "nst", "r c", "r ch", "sis", "tan", "ter c"},
	"+#% monster elemental resistance": {"%", "% m", "% mo", "+", "ance", "ele", "emen", "er e", "ist", "lem", "mon", "nst", "r e", "sis", "tan"},
	"+#% monster physical damage reduction": {"%", "% m", "% mo", "+", "al d", "ama", "cti", "ctio", "hys", "l d", "mon", "nst", "r p", "uc", "uct"},
	"all monster damage from hits always ignites": {"ama", "e f", "from", "hit", "ite", "lw", "mon", "nst", "r d", "s a", "s i"},
	"area contains many totems": {"ains", "area", "ems", "ont", "rea", "s m"},
	"area contains two unique bosses": {"ains", "area", "iq", "ont", "rea", "s t", "ses", "tw", "ue"},
	"area has increased monster variety": {"a h", "area", "ase", "ased", "cre", "d mo", "ed mo", "ety", "has", "mon", "nst", "rea", "s i", "s in", "sed m"},
	"area has patches of burning ground": {"a h", "area", "atc", "es o", "f b", "has", "ning", "rea", "s o", "s of", "s p", "tc"},
	"area has patches of chilled ground": {"a h", "area", "atc", "d gr", "es o", "f c", "has", "hil", "rea", "s o", "s of", "s p", "tc"},
	"area has patches of desecrated ground": {"a h", "area", "atc", "d gr", "es o", "f d", "has", "rea", "s o", "s of", "s p", "tc"},
	"area has patches of shocked ground which increase damage taken by #%": {"%", "a h", "ama", "area", "ase", "atc", "by", "cre", "d gr", "d w", "e d", "e ta", "es o", "f s", "has", "rea", "s o", "s of", "s p", "tak", "tc"},
	"area is inhabited by # additional rogue exile": {"add", "area", "by", "d b", "d by", "e e", "gu", "ite", "iti", "nh", "rea", "s i", "s in", "ue"},
	"area is inhabited by # additional rogue exiles": {"add", "area", "by", "d b", "d by", "e e", "gu", "iles", "ite", "iti", "les", "nh", "rea", "s i", "s in", "ue", "xiles"},
	"area is inhabited by # additional rogue exiles§area is inhabited by # additional rogue exile": {"iles", "les", "xiles"},
	"area is inhabited by abominations": {"area", "bom", "by", "d b", "d by", "ite", "nh", "rea", "s i", "s in", "y a"},
	"area is inhabited by animals": {"als", "ani", "area", "by", "d b", "d by", "ite", "nh", "rea", "s i", "s in", "y a"},
	"area is inhabited by cultists of kitava": {"area", "by", "cul", "d b", "d by", "ist", "ite", "nh", "rea", "s i", "s in", "s o", "s of", "sts", "ts o", "y c"},
	"area is inhabited by demons": {"area", "by", "d b", "d by", "emo", "ite", "mon", "nh", "rea", "s i", "s in"},
	"area is inhabited by ghosts": {"area", "by", "d b", "d by", "gho", "ite", "nh", "rea", "s i", "s in", "sts", "y g"},
	"area is inhabited by goatmen": {"area", "by", "d b", "d by", "ite", "nh", "oa", "rea", "s i", "s in", "y g"},
	"area is inhabited by humanoids": {"area", "by", "d b", "d by", "hum", "ite", "nh", "oi", "oid", "rea", "s i", "s in"},
	"area is inhabited by lunaris fanatics": {"ana", "area", "by", "cs", "d b", "d by", "ite", "lu", "lun", "nh", "rea", "s f", "s i", "s in", "tic"},
	"area is inhabited by ranged monsters": {"ang", "area", "by", "d b", "d by", "d mo", "d monsters", "ed mo", "ite", "mon", "nh", "nst", "rea", "s i", "s in", "ters", "y r"},
	"area is inhabited by sea witches and their spawn": {"area", "aw", "by", "by s", "d b", "d by", "ite", "nh", "rea", "s a", "s an", "s i", "s in", "tc", "wi"},
	"area is inhabited by skeletons": {"area", "by", "by s", "d b", "d by", "ele", "eto", "ite", "nh", "rea", "s i", "s in", "sk"},
	"area is inhabited by solaris fanatics": {"ana", "area", "by", "by s", "cs", "d b", "d by", "ite", "lar", "nh", "rea", "s f", "s i", "s in", "tic"},
	"area is inhabited by undead": {"area", "by", "d b", "d by", "dea", "ite", "nh", "rea", "s i", "s in", "y u"},
	"cannot leech from monsters": {"ech", "from", "lee", "mon", "nno", "nst", "ters"},
	"magic monster packs each have a bloodline mod": {"ack", "dl", "e a", "e mo", "e mod", "gi", "h h", "hav", "mod", "mon", "nst", "r p", "ve a"},
	"monsters are hexproof": {"hex", "mon", "nst", "rs a", "rs ar", "s a", "s ar", "s are", "ters", "xp"},
	"monsters cannot be affected by elemental ailments": {"af", "by", "d b", "d by", "e a", "ect", "ele", "emen", "ff", "lem", "lm", "mon", "nno", "nst", "ot b", "rs c", "s c", "t b", "ters", "ters c"},
	"monsters cannot be stunned": {"e s", "mon", "nno", "nst", "ot b", "rs c", "s c", "t b", "ters", "ters c"},
	"monsters cannot be taunted": {"be t", "e ta", "mon", "nno", "nst", "ot b", "rs c", "s c", "t b", "ters", "ters c"},
	"monsters deal #% extra physical damage as cold": {"%", "% e", "a p", "al d", "ama", "as c", "dea", "e a", "eal", "hys", "l d", "mon", "nst", "s c", "ters", "xt"},
	"monsters deal #% extra physical damage as fire": {"%", "% e", "a p", "al d", "ama", "as f", "dea", "e a", "eal", "fir", "hys", "l d", "mon", "nst", "s f", "ters", "xt"},
	"monsters deal #% extra physical damage as lightning": {"%", "% e", "a p", "al d", "ama", "dea", "e a", "eal", "hys", "l d", "mon", "ning", "nst", "ters", "tn", "xt"},
	"monsters fire # additional projectiles": {"add", "cti", "ect", "fir", "iles", "iti", "je", "les", "mon", "nst", "rs f", "s f", "ters"},
	"monsters gain a frenzy charge on hit": {"arg", "hit", "mon", "n a", "n h", "nst", "nz", "s g", "s gain a f", "ters", "ters g", "y c"},
	"monsters gain a power charge on hit": {"a p", "arg", "hit", "mon", "n a", "n h", "nst", "pow", "r c", "r ch", "s g", "s gain a p", "ters", "ters g"},
	"monsters gain an endurance charge on hit": {"ance", "arg", "dur", "e cha", "hit", "mon", "n a", "n h", "nst", "s g", "s gain an", "ters", "ters g", "ura"},
	"monsters have #% chance to avoid elemental ailments": {"%", "% c", "ance", "avo", "ce t", "d e", "d el", "e to", "e to a", "ele", "emen", "hanc", "hav", "lem", "lm", "mon", "nst", "o a", "oi", "oid", "rs h", "s h", "ters", "ters h"},
	"monsters have #% chance to gain a frenzy charge on hit": {"%", "% c", "ance", "arg", "ce t", "e to", "hanc", "hav", "hit", "mon", "n a", "n h", "nst", "nz", "o g", "o gain a f", "rs h", "s h", "ters", "ters h", "y c"},
	"monsters have #% chance to gain a power charge on hit": {"%", "% c", "a p", "ance", "arg", "ce t", "e to", "hanc", "hav", "hit", "mon", "n a", "n h", "nst", "o g", "o gain a p", "pow", "r c", "r ch", "rs h", "s h", "ters", "ters h"},
	"monsters have #% chance to gain an endurance charge on hit": {"%", "% c", "ance", "arg", "ce t", "dur", "e cha", "e to", "hanc", "hav", "hit", "mon", "n a", "n h", "nst", "o g", "o gain an", "rs h", "s h", "ters", "ters h", "ura"},
	"monsters have #% increased accuracy rating": {"%", "% i", "ase", "ased", "cc", "cre", "d a", "hav", "mon", "nst", "rea", "rs h", "s h", "ters", "ters h", "ura", "y r", "y rat"},
	"monsters have #% increased area of effect": {"%", "% i", "a o", "a of", "area", "ase", "ased", "cre", "d a", "d ar", "ect", "eff", "f e", "ff", "hav", "mon", "nst", "rea", "rs h", "s h", "ters", "ters h"},
	"monsters have #% increased critical strike chance": {"%", "% i", "ance", "ase", "ased", "cre", "e cha", "hanc", "hav", "ik", "iti", "ke c", "mon", "nst", "rea", "rs h", "s h", "ters", "ters h", "tic"},
	"monsters have a #% chance to avoid poison, blind, and bleeding": {"%", "% c", ",", "ance", "avo", "ce t", "d b", "d,", "e a", "e to", "e to a", "eed", "hanc", "hav", "iso", "lee", "mon", "nst", "o a", "oi", "oid", "poi", "rs h", "s h", "s have a", "ters", "ters h", "ve a"},
	"monsters have a #% chance to cause elemental ailments on hit": {"%", "% c", "ance", "cau", "ce t", "e a", "e e", "e to", "ele", "emen", "hanc", "hav", "hit", "lem", "lm", "mon", "n h", "nst", "rs h", "s h", "s have a", "s o", "s on", "ters", "ters h", "ts o", "ve a"},
	"monsters poison on hit": {"hit", "iso", "mon", "n h", "n o", "nst", "oi", "poi", "s p", "ters"},
	"monsters reflect #% of elemental damage": {"%", "% o", "al d", "ama", "ect", "ele", "emen", "f e", "f el", "l d", "lem", "mon", "nst", "ters"},
	"monsters reflect #% of physical damage": {"%", "% o", "al d", "ama", "ect", "f p", "hys", "l d", "mon", "nst", "ters"},
	"monsters take #% reduced extra damage from critical strikes": {"%", "% r", "a d", "ama", "d e", "e f", "from", "ik", "iti", "mon", "nst", "s t", "tak", "ters", "tic", "uc", "xt"},
	"monsters' action speed cannot be modified to below base value": {"' a", "ase", "cti", "ctio", "e mo", "e mod", "eed", "if", "lu", "mod", "mon", "nno", "nst", "o b", "ot b", "pee", "s'", "spe", "t b", "ters", "ue"},
	"monsters' skills chain # additional times": {"' s", "add", "chai", "iti", "mon", "nst", "s c", "s'", "sk", "ters"},
	"players and monsters fire # additional projectiles": {"add", "cti", "d mo", "d monsters", "ect", "fir", "iles", "iti", "je", "lay", "les", "mon", "nd m", "nst", "rs a", "rs f", "s a", "s an", "s f", "ters", "ye", "yers", "yers a"},
	"players and monsters fire # additional projectiles§monsters fire # additional projectiles": {"d mo", "d monsters", "lay", "nd m", "rs a", "s a", "s an", "ye", "yers", "yers a"},
	"players are cursed with elemental weakness": {"d w", "ele", "emen", "ess", "h e", "ith", "kn", "lay", "lem", "rs a", "rs ar", "s a", "s ar", "s are", "wi", "ye", "yers", "yers a"},
	"players are cursed with enfeeble": {"d w", "ebl", "h e", "ith", "lay", "rs a", "rs ar", "s a", "s ar", "s are", "wi", "ye", "yers", "yers a"},
	"players are cursed with temporal chains": {"ains", "chai", "d w", "h t", "ith", "lay", "rs a", "rs ar", "s a", "s ar", "s are", "wi", "ye", "yers", "yers a"},
	"players are cursed with vulnerability": {"d w", "ith", "lay", "ln", "rs a", "rs ar", "s a", "s ar", "s are", "wi", "ye", "yers", "yers a"},
	"players cannot inflict exposure": {"fli", "lay", "nno", "rs c", "s c", "xp", "ye", "yers", "yers c"},
	"players cannot regenerate life, mana or energy shield": {",", "a o", "ana", "e,", "ene", "gy", "if", "ife", "lay", "nno", "r e", "rs c", "s c", "ye", "yers", "yers c"},
	"players gain #% reduced flask charges": {"%", "% r", "arg", "ask", "lay", "s g", "sk", "uc", "ye", "yers"},
	"players have #% less area of effect": {"%", "% l", "a o", "a of", "area", "ect", "eff", "ess", "f e", "ff", "hav", "lay", "les", "rea", "rs h", "s a", "s ar", "s are", "s area", "s h", "ss a", "ye", "yers", "yers h"},
	"players have #% less armour": {"%", "% l", "ess", "hav", "lay", "les", "rs h", "s a", "s ar", "s arm", "s h", "ss a", "ye", "yers", "yers h"},
	"players have #% less recovery rate of life and energy shield": {"%", "% l", "d e", "e a", "ene", "ess", "f l", "gy", "hav", "if", "ife", "lay", "les", "rs h", "s h", "y r", "y rat", "ye", "yers", "yers h"},
	"players have #% reduced chance to block": {"%", "% r", "ance", "ce t", "d ch", "e to", "hanc", "hav", "lay", "o b", "rs h", "s h", "uc", "ye", "yers", "yers h"},
	"players have #% to amount of suppressed spell damage prevented": {"%", "ama", "ess", "ev", "f s", "hav", "l d", "lay", "o a", "rs h", "s h", "spe", "ye", "yers", "yers h"},
	"players have point blank": {"ank", "hav", "lay", "oi", "poi", "rs h", "s h", "t b", "ye", "yers", "yers h"},
	"rare monsters each have a nemesis mod": {"a n", "e a", "e mo", "e mon", "h h", "hav", "mod", "mon", "nem", "nst", "rar", "re m", "s m", "s mo", "sis", "ters", "ve a"},
	"slaying enemies close together attracts monsters from beyond": {"att", "cl", "cts", "e to", "ene", "from", "lay", "mon", "nem", "nst", "r a", "rs f", "s c", "s f", "s m", "s mo", "ters"},
	"slaying enemies close together has a #% chance to attract monsters from beyond": {"%", "% c", "ance", "att", "ce t", "cl", "e to", "e to a", "ene", "from", "hanc", "has", "lay", "mon", "nem", "nst", "o a", "r h", "rs f", "s a", "s c", "s f", "ters"},
	"unique boss deals #% increased damage": {"%", "% i", "als", "ama", "ase", "ased", "cre", "d d", "dea", "eal", "iq", "rea", "ue"},
	"unique boss has #% increased area of effect": {"%", "% i", "a o", "a of", "area", "ase", "ased", "cre", "d a", "d ar", "ect", "eff", "f e", "ff", "has", "iq", "rea", "s h", "ss h", "ue"},
	"unique boss has #% increased attack and cast speed": {"%", "% i", "ack", "ase", "ased", "att", "cre", "d a", "eed", "has", "iq", "k a", "pee", "rea", "s h", "spe", "ss h", "st s", "t spe", "tac", "ue"},
	"unique boss has #% increased life": {"%", "% i", "ase", "ased", "cre", "d li", "has", "if", "ife", "iq", "rea", "s h", "ss h", "ue"},
}