subnames = {
	"monsters fire # additional projectiles": ['players and monsters fire # additional projectiles'],
	"area is inhabited by # additional rogue exile": ['area is inhabited by # additional rogue exiles'],
}

ngrams = {
	"#% increased monster attack speed": {"%", "% i", "% increased m", "ase", "ased", "att", "cre", "d mo", "eas", "ed mo", "eed", "k sp", "pee", "r a", "rea", "sed m", "spe", "tac"},
	"#% increased monster cast speed": {"%", "% i", "% increased m", "ase", "ased", "cre", "d mo", "eas", "ed mo", "eed", "pee", "r c", "r ca", "rea", "sed m", "spe", "st s", "t spe", "ter c"},
	"#% increased monster damage": {"%", "% i", "% increased m", "ama", "ase", "ased", "cre", "d mo", "d monster d", "eas", "ed mo", "r d", "rea", "sed m"},
	"#% increased monster movement speed": {"%", "% i", "% increased m", "ase", "ased", "cre", "d mo", "eas", "ed mo", "eed", "emen", "mov", "pee", "rea", "sed m", "spe", "t spe"},
	"#% less effect of curses on monsters": {"%", "% l", "ct o", "ect", "eff", "es o", "es on", "ess", "f c", "fec", "ff", "les", "n m", "s o", "s on", "ses", "ters"},
	"#% maximum player resistances": {"%", "% m", "ance", "ax", "ces", "ist", "lay", "sis", "tan", "ye"},
	"#% more magic monsters": {"%", "% m", "% mo", "e ma", "gi", "more", "ore m", "re m", "ters"},
	"#% more monster life": {"%", "% m", "% mo", "e mo", "e mon", "if", "ife", "more", "ore m", "r li", "re m"},
	"#% more rare monsters": {"%", "% m", "% mo", "e mo", "e mon", "e ra", "more", "rare", "re m", "ters"},
	"+#% monster chaos resistance": {"%", "% m", "% mo", "+", "ance", "ao", "ist", "r c", "r ch", "sis", "tan", "ter c"},
	"+#% monster elemental resistance": {"%", "% m", "% mo", "+", "ance", "ele", "emen", "er e", "ist", "lem", "r e", "sis", "tan"},
	"+#% monster physical damage reduction": {"%", "% m", "% mo", "+", "al d", "ama", "cti", "ctio", "hys", "l d", "uc", "uct"},
	"all monster damage from hits always ignites": {"ama", "e f", "from", "hit", "lw", "r d", "s a", "s i"},
	"area contains many totems": {"ains", "area", "ems", "ont", "rea", "s m", "s ma"},
	"area contains two unique bosses": {"ains", "area", "iq", "ont", "rea", "s t", "ses", "sses", "tw", "ue"},
	"area has increased monster variety": {"a h", "area", "ase", "ased", "cre", "d mo", "eas", "ed mo", "ety", "has", "rea", "s i", "s in", "sed m"},
	"area has patches of burning ground": {"a h", "area", "as p", "atc", "es o", "f b", "has", "ning", "rea", "s o", "s of", "s p", "tc"},
	"area has patches of chilled ground": {"a h", "area", "as p", "atc", "d gr", "es o", "f c", "has", "hil", "rea", "s o", "s of", "s of c", "s p", "tc"},
	"area has patches of desecrated ground": {"a h", "area", "as p", "atc", "d gr", "es o", "f d", "has", "rea", "s o", "s of", "s p", "sec", "tc"},
	"area has patches of shocked ground which increase damage taken by #%": {"%", "a h", "ama", "area", "as p", "ase", "atc", "by", "cre", "d gr", "d w", "e d", "e ta", "eas", "es o", "f s", "has", "rea", "s o", "s of", "s p", "tak", "tc"},
	"area is inhabited by # additional rogue exile": {"add", "area", "by", "d b", "d by", "e e", "gu", "iti", "nh", "rea", "s i", "s in", "ue"},
	"area is inhabited by # additional rogue exiles": {"add", "area", "by", "d b", "d by", "e e", "gu", "iles", "iti", "les", "nh", "rea", "s i", "s in", "ue", "xiles"},
	"area is inhabited by # additional rogue exiles§area is inhabited by # additional rogue exile": {"iles", "les", "xiles"},
	"area is inhabited by abominations": {"area", "bom", "by", "by a", "d b", "d by", "nh", "rea", "s i", "s in", "y a"},
	"area is inhabited by animals": {"als", "ani", "area", "by", "by a", "d b", "d by", "nh", "rea", "s i", "s in", "y a", "y an"},
	"area is inhabited by cultists of kitava": {"area", "by", "cul", "d b", "d by", "ist", "nh", "rea", "s i", "s in", "s o", "s of", "sts", "ts o", "y c"},
	"area is inhabited by demons": {"area", "by", "d b", "d by", "emo", "nh", "rea", "s i", "s in"},
	"area is inhabited by ghosts": {"area", "by", "d b", "d by", "gho", "nh", "rea", "s i", "s in", "sts", "y g"},
	"area is inhabited by goatmen": {"area", "by", "d b", "d by", "nh", "oa", "rea", "s i", "s in", "y g"},
	"area is inhabited by humanoids": {"area", "by", "d b", "d by", "hum", "nh", "oi", "oid", "rea", "s i", "s in"},
	"area is inhabited by lunaris fanatics": {"ana", "area", "by", "cs", "d b", "d by", "lu", "lun", "nh", "rea", "s f", "s i", "s in", "tic"},
	"area is inhabited by ranged monsters": {"ang", "area", "by", "d b", "d by", "d mo", "d monsters", "ed mo", "nh", "rea", "s i", "s in", "ters", "y r"},
	"area is inhabited by sea witches and their spawn": {"area", "aw", "by", "by s", "d b", "d by", "es a", "nh", "rea", "s a", "s an", "s i", "s in", "tc", "wi"},
	"area is inhabited by skeletons": {"area", "by", "by s", "d b", "d by", "ele", "eto", "nh", "rea", "s i", "s in", "sk"},
	"area is inhabited by solaris fanatics": {"ana", "area", "by", "by s", "cs", "d b", "d by", "lar", "nh", "rea", "s f", "s i", "s in", "tic"},
	"area is inhabited by undead": {"area", "by", "d b", "d by", "dea", "nh", "rea", "s i", "s in", "y u"},
	"areas have patches of consecrated ground": {"area", "as h", "atc", "d gr", "eas", "es o", "f c", "hav", "rea", "s h", "s ha", "s hav", "s o", "s of", "s of c", "sec", "tc"},
	"buffs on players expire #% faster": {"%", "ff", "fs", "ire", "lay", "rs e", "s ex", "s o", "s on", "xp", "ye", "yers"},
	"cannot leech from monsters": {"ech", "from", "lee", "nno", "ters"},
	"magic monster packs each have a bloodline mod": {"acks", "dl", "e a", "e mo", "e mod", "gi", "h h", "hav", "mod", "ve a"},
	"monsters are hexproof": {"hex", "rs a", "rs ar", "s a", "s ar", "s are", "ters", "xp"},
	"monsters blind on hit": {"bli", "hit", "ind", "n h", "s b", "ters"},
	"monsters cannot be affected by elemental ailments": {"af", "by", "d b", "d by", "e a", "ect", "ele", "emen", "fec", "ff", "lem", "lm", "nno", "rs c", "s c", "t b", "ters", "ters c"},
	"monsters cannot be stunned": {"e s", "nno", "rs c", "s c", "t b", "ters", "ters c"},
	"monsters cannot be taunted": {"be t", "e ta", "nno", "rs c", "s c", "t b", "ters", "ters c"},
	"monsters deal #% extra physical damage as cold": {"%", "% e", "a p", "al d", "ama", "as c", "dea", "e a", "e as", "eal", "hys", "l d", "s c", "s co", "s d", "ters", "xt"},
	"monsters deal #% extra physical damage as fire": {"%", "% e", "a p", "al d", "ama", "as f", "as fi", "dea", "e a", "e as", "eal", "fir", "hys", "ire", "l d", "s d", "s f", "ters", "xt"},
	"monsters deal #% extra physical damage as lightning": {"%", "% e", "a p", "al d", "ama", "dea", "e a", "e as", "eal", "hys", "l d", "ning", "s d", "ters", "tn", "xt"},
	"monsters fire # additional projectiles": {"add", "cti", "ect", "fir", "iles", "ire", "iti", "je", "les", "rs f", "s f", "ters"},
	"monsters gain #% of maximum life as extra maximum energy shield": {"%", "% o", "a m", "ax", "e a", "e as", "ene", "fe a", "gai", "gy", "if", "ife", "s ex", "s g", "ters", "ters g", "xt"},
	"monsters gain a frenzy charge on hit": {"a f", "arg", "gai", "hit", "n a", "n h", "nz", "s g", "s gain a", "s gain a f", "ters", "ters g", "y c"},
	"monsters gain a power charge on hit": {"a p", "a po", "arg", "gai", "hit", "n a", "n h", "pow", "r c", "r ch", "s g", "s gain a", "s gain a p", "ters", "ters g"},
	"monsters gain an endurance charge on hit": {"ance", "arg", "dur", "e cha", "gai", "hit", "n a", "n e", "n h", "s g", "s gain a", "s gain an", "ters", "ters g", "ura"},
	"monsters have #% chance to avoid elemental ailments": {"%", "% c", "ance", "avo", "ce t", "d e", "d el", "e to", "e to a", "ele", "emen", "hanc", "hav", "lem", "lm", "o a", "oi", "oid", "rs h", "rs ha", "s h", "s ha", "s hav", "ters", "ters h", "ters ha"},
	"monsters have #% chance to blind on hit": {"%", "% c", "ance", "bli", "ce t", "e to", "hanc", "hav", "hit", "ind", "n h", "o b", "o bl", "o bli", "rs h", "rs ha", "s h", "s ha", "s hav", "ters", "ters h", "ters ha"},
	"monsters have #% chance to gain a frenzy charge on hit": {"%", "% c", "a f", "ance", "arg", "ce t", "e to", "gai", "hanc", "hav", "hit", "n a", "n h", "nz", "o g", "o gain a f", "rs h", "rs ha", "s h", "s ha", "s hav", "ters", "ters h", "ters ha", "y c"},
	"monsters have #% chance to gain a power charge on hit": {"%", "% c", "a p", "a po", "ance", "arg", "ce t", "e to", "gai", "hanc", "hav", "hit", "n a", "n h", "o g", "o gain a p", "pow", "r c", "r ch", "rs h", "rs ha", "s h", "s ha", "s hav", "ters", "ters h", "ters ha"},
	"monsters have #% chance to gain an endurance charge on hit": {"%", "% c", "ance", "arg", "ce t", "dur", "e cha", "e to", "gai", "hanc", "hav", "hit", "n a", "n e", "n h", "o g", "o gain an", "rs h", "rs ha", "s h", "s ha", "s hav", "ters", "ters h", "ters ha", "ura"},
	"monsters have #% chance to hinder on hit with spells": {"%", "% c", "ance", "ce t", "e to", "h s", "hanc", "hav", "hit", "ind", "ith", "n h", "o h", "pel", "rs h", "rs ha", "s h", "s ha", "s hav", "spe", "t w", "ters", "ters h", "ters ha", "wi"},
	"monsters have #% chance to impale with attacks": {"%", "% c", "acks", "ale", "ance", "att", "ce t", "e to", "e w", "h a", "hanc", "hav", "ith", "o i", "rs h", "rs ha", "s h", "s ha", "s hav", "tac", "ters", "ters h", "ters ha", "wi"},
	"monsters have #% chance to maim on hit with attacks": {"%", "% c", "acks", "aim", "ance", "att", "ce t", "e to", "h a", "hanc", "hav", "hit", "ith", "n h", "o m", "rs h", "rs ha", "s h", "s ha", "s hav", "t w", "tac", "ters", "ters h", "ters ha", "wi"},
	"monsters have #% chance to steal power, frenzy and endurance charges on hit": {"%", "% c", ",", "ance", "arg", "ce t", "d e", "d en", "dur", "e cha", "e to", "eal", "es o", "es on", "ges", "hanc", "hav", "hit", "n h", "nz", "o s", "o st", "pow", "r,", "rs h", "rs ha", "s h", "s ha", "s hav", "s o", "s on", "s on h", "ters", "ters h", "ters ha", "ura", "y a", "y an"},
	"monsters have #% chance to suppress spell damage": {"%", "% c", "ama", "ance", "ce t", "e to", "ess", "hanc", "hav", "l d", "o s", "o su", "pel", "pp", "rs h", "rs ha", "s h", "s ha", "s hav", "s s", "spe", "ters", "ters h", "ters ha"},
	"monsters have #% increased accuracy rating": {"%", "% i", "ase", "ased", "cc", "cre", "d a", "d ac", "eas", "hav", "rea", "rs h", "rs ha", "s h", "s ha", "s hav", "ters", "ters h", "ters ha", "ura", "y r", "y rat"},
	"monsters have #% increased area of effect": {"%", "% i", "a o", "a of", "area", "ase", "ased", "cre", "d a", "d ar", "eas", "ect", "eff", "f e", "fec", "ff", "hav", "rea", "rs h", "rs ha", "s h", "s ha", "s hav", "ters", "ters h", "ters ha"},
	"monsters have #% increased critical strike chance": {"%", "% i", "ance", "ase", "ased", "cre", "e cha", "eas", "hanc", "hav", "ik", "iti", "ke c", "rea", "rs h", "rs ha", "s h", "s ha", "s hav", "ters", "ters h", "ters ha", "tic"},
	"monsters have a #% chance to avoid poison, impale, and bleeding": {"%", "% c", ",", "ale", "ance", "avo", "ce t", "d b", "e a", "e to", "e to a", "e,", "eed", "hanc", "hav", "iso", "lee", "n,", "o a", "oi", "oid", "rs h", "rs ha", "s h", "s ha", "s hav", "s have a", "ters", "ters h", "ters ha", "ve a"},
	"monsters have a #% chance to cause elemental ailments on hit": {"%", "% c", "ance", "cau", "ce t", "e a", "e e", "e to", "ele", "emen", "hanc", "hav", "hit", "lem", "lm", "n h", "rs h", "rs ha", "s h", "s ha", "s hav", "s have a", "s o", "s on", "s on h", "ters", "ters h", "ters ha", "ts o", "ve a"},
	"monsters hinder on hit with spells": {"h s", "hit", "ind", "ith", "n h", "pel", "rs h", "s h", "s hi", "spe", "t w", "ters", "ters h", "wi"},
	"monsters inflict impale with attacks": {"acks", "ale", "att", "ct i", "e w", "fli", "h a", "ith", "s i", "s in", "tac", "ters", "wi"},
	"monsters maim on hit with attacks": {"acks", "aim", "att", "h a", "hit", "ith", "n h", "rs m", "s m", "s ma", "t w", "tac", "ters", "wi"},
	"monsters poison on hit": {"hit", "iso", "n h", "n o", "oi", "s p", "ters"},
	"monsters reflect #% of elemental damage": {"%", "% o", "al d", "ama", "ect", "efl", "ele", "emen", "f e", "f el", "l d", "lem", "ters"},
	"monsters reflect #% of physical damage": {"%", "% o", "al d", "ama", "ect", "efl", "f p", "hys", "l d", "ters"},
	"monsters steal power, frenzy and endurance charges on hit": {",", "ance", "arg", "d e", "d en", "dur", "e cha", "eal", "es o", "es on", "ges", "hit", "n h", "nz", "pow", "r,", "rs s", "s o", "s on", "s on h", "s s", "ters", "ura", "y a", "y an"},
	"monsters take #% reduced extra damage from critical strikes": {"%", "% r", "a d", "ama", "d e", "e f", "ed e", "from", "ik", "iti", "s t", "tak", "ters", "tic", "uc", "xt"},
	"monsters' action speed cannot be modified to below base value": {"' a", "ase", "cti", "ctio", "e mo", "e mod", "eed", "if", "lu", "mod", "nno", "o b", "pee", "s'", "spe", "t b", "ters", "ue"},
	"monsters' skills chain # additional times": {"' s", "add", "chai", "iti", "kil", "s c", "s'", "sk", "ters"},
	"players and monsters fire # additional projectiles": {"add", "cti", "d mo", "d monsters", "ect", "fir", "iles", "ire", "iti", "je", "lay", "les", "nd m", "rs a", "rs f", "s a", "s an", "s f", "ters", "ye", "yers", "yers a"},
	"players and monsters fire # additional projectiles§monsters fire # additional projectiles": {"d mo", "d monsters", "lay", "nd m", "rs a", "s a", "s an", "ye", "yers", "yers a"},
	"players are cursed with elemental weakness": {"d w", "d wi", "ele", "emen", "ess", "h e", "ith", "kn", "lay", "lem", "rs a", "rs ar", "s a", "s ar", "s are", "wi", "ye", "yers", "yers a"},
	"players are cursed with enfeeble": {"d w", "d wi", "ebl", "h e", "ith", "lay", "rs a", "rs ar", "s a", "s ar", "s are", "wi", "ye", "yers", "yers a"},
	"players are cursed with temporal chains": {"ains", "chai", "d w", "d wi", "h t", "ith", "lay", "rs a", "rs ar", "s a", "s ar", "s are", "wi", "ye", "yers", "yers a"},
	"players are cursed with vulnerability": {"d w", "d wi", "ith", "lay", "ln", "rs a", "rs ar", "s a", "s ar", "s are", "wi", "ye", "yers", "yers a"},
	"players cannot inflict exposure": {"fli", "lay", "nno", "osu", "pos", "rs c", "s c", "xp", "ye", "yers", "yers c"},
	"players cannot regenerate life, mana or energy shield": {",", ", m", "a o", "ana", "e,", "ene", "gy", "if", "ife", "lay", "nno", "r e", "rs c", "s c", "ye", "yers", "yers c"},
	"players gain #% reduced flask charges": {"%", "% r", "arg", "ask", "gai", "ges", "lay", "s g", "sk", "uc", "ye", "yers"},
	"players have #% less accuracy rating": {"%", "% l", "cc", "ess", "hav", "lay", "les", "rs h", "rs ha", "s a", "s ac", "s h", "s ha", "s hav", "ss a", "ura", "y r", "y rat", "ye", "yers", "yers h"},
	"players have #% less area of effect": {"%", "% l", "a o", "a of", "area", "ect", "eff", "ess", "f e", "fec", "ff", "hav", "lay", "les", "rea", "rs h", "rs ha", "s a", "s ar", "s are", "s area", "s h", "s ha", "s hav", "ss a", "ss ar", "ye", "yers", "yers h"},
	"players have #% less armour": {"%", "% l", "ess", "hav", "lay", "les", "rs h", "rs ha", "s a", "s ar", "s arm", "s h", "s ha", "s hav", "ss a", "ss ar", "ye", "yers", "yers h"},
	"players have #% less cooldown recovery rate": {"%", "% l", "coo", "ecov", "ess", "hav", "lay", "les", "rs h", "rs ha", "s c", "s co", "s h", "s ha", "s hav", "y r", "y rat", "ye", "yers", "yers h"},
	"players have #% less recovery rate of life and energy shield": {"%", "% l", "d e", "d en", "e a", "ecov", "ene", "ess", "f l", "fe a", "gy", "hav", "if", "ife", "lay", "les", "rs h", "rs ha", "s h", "s ha", "s hav", "y r", "y rat", "ye", "yers", "yers h"},
	"players have #% reduced chance to block": {"%", "% r", "ance", "ce t", "d ch", "e to", "hanc", "hav", "lay", "o b", "o bl", "rs h", "rs ha", "s h", "s ha", "s hav", "uc", "ye", "yers", "yers h"},
	"players have #% reduced effect of non-curse auras from skills": {"%", "% r", "-", "as f", "ct o", "d e", "e a", "ect", "ed e", "eff", "fec", "ff", "from", "hav", "kil", "lay", "rs h", "rs ha", "s f", "s fr", "s h", "s ha", "s hav", "sk", "uc", "ura", "ye", "yers", "yers h"},
	"players have #% to amount of suppressed spell damage prevented": {"%", "ama", "ess", "esse", "ev", "f s", "hav", "l d", "lay", "o a", "pel", "pp", "rs h", "rs ha", "s h", "s ha", "s hav", "spe", "ye", "yers", "yers h"},
	"rare monsters each have a nemesis mod": {"a n", "e a", "e mo", "e mon", "h h", "hav", "mod", "nem", "rare", "re m", "rs e", "s m", "s mo", "sis", "ters", "ve a"},
	"slaying enemies close together attracts monsters from beyond": {"att", "cts", "e to", "ene", "from", "lay", "nem", "r a", "rs f", "s c", "s f", "s fr", "s m", "s mo", "ters", "yi"},
	"slaying enemies close together has a #% chance to attract monsters from beyond": {"%", "% c", "ance", "att", "ce t", "e to", "e to a", "ene", "from", "hanc", "has", "lay", "nem", "o a", "r h", "rs f", "s a", "s c", "s f", "s fr", "ters", "yi"},
	"unique boss deals #% increased damage": {"%", "% i", "als", "ama", "ase", "ased", "cre", "d d", "dea", "eal", "eas", "iq", "rea", "s d", "ue"},
	"unique boss has #% increased area of effect": {"%", "% i", "a o", "a of", "area", "ase", "ased", "cre", "d a", "d ar", "eas", "ect", "eff", "f e", "fec", "ff", "has", "iq", "rea", "s h", "s ha", "ss h", "ue"},
	"unique boss has #% increased attack and cast speed": {"%", "% i", "ase", "ased", "att", "cre", "d a", "eas", "eed", "has", "iq", "k a", "pee", "rea", "s h", "s ha", "spe", "ss h", "st s", "t spe", "tac", "ue"},
	"unique boss has #% increased life": {"%", "% i", "ase", "ased", "cre", "d li", "eas", "has", "if", "ife", "iq", "rea", "s h", "s ha", "ss h", "ue"},
	"unique bosses are possessed": {"es a", "ess", "esse", "iq", "pos", "poss", "s a", "s ar", "s are", "ses", "sses", "ue"},
}