subnames = {
	"monsters fire # additional projectiles": ['players and monsters fire # additional projectiles'],
	"area is inhabited by # additional rogue exile": ['area is inhabited by # additional rogue exiles'],
}

ngrams = {
	"#% increased monster attack speed": {"%", "% i", "% increased m", "ack", "ase", "ased", "att", "cre", "d mo", "eas", "ed mo", "eed", "k s", "mon", "nst", "pee", "r a", "rea", "sed m", "spe", "ster", "tac"},
	"#% increased monster cast speed": {"%", "% i", "% increased m", "ase", "ased", "cre", "d mo", "eas", "ed mo", "eed", "mon", "nst", "pee", "r c", "r ca", "rea", "sed m", "spe", "st s", "ster", "t spe", "ter c"},
	"#% increased monster damage": {"%", "% i", "% increased m", "ama", "ase", "ased", "cre", "d mo", "d monster d", "eas", "ed mo", "mon", "nst", "r d", "rea", "sed m", "ster"},
	"#% increased monster movement speed": {"%", "% i", "% increased m", "ase", "ased", "cre", "d mo", "eas", "ed mo", "eed", "emen", "mon", "mov", "nst", "pee", "rea", "sed m", "spe", "ster", "t spe"},
	"#% less effect of curses on monsters": {"%", "% l", "ct o", "ect", "eff", "es o", "es on", "ess", "f c", "fec", "ff", "les", "mon", "n m", "nst", "s o", "s on", "ses", "ster", "ters"},
	"#% maximum player resistances": {"%", "% m", "ance", "ax", "ces", "ist", "lay", "sis", "tan", "ye"},
	"#% more magic monsters": {"%", "% m", "% mo", "e ma", "gi", "mon", "more", "nst", "ore m", "re m", "ster", "ters"},
	"#% more monster life": {"%", "% m", "% mo", "e mo", "e mon", "if", "ife", "mon", "more", "nst", "ore m", "r li", "re m", "ster"},
	"#% more rare monsters": {"%", "% m", "% mo", "e mo", "e mon", "e ra", "mon", "more", "nst", "rar", "re m", "ster", "ters"},
	"+#% monster chaos resistance": {"%", "% m", "% mo", "+", "ance", "ao", "ist", "mon", "nst", "r c", "r ch", "sis", "ster", "tan", "ter c"},
	"+#% monster elemental resistance": {"%", "% m", "% mo", "+", "ance", "ele", "emen", "er e", "ist", "lem", "mon", "nst", "r e", "sis", "ster", "tan"},
	"+#% monster physical damage reduction": {"%", "% m", "% mo", "+", "al d", "ama", "cti", "ctio", "hys", "l d", "mon", "nst", "r p", "ster", "uc", "uct"},
	"all monster damage from hits always ignites": {"ama", "e f", "from", "hit", "ite", "lw", "mon", "nst", "r d", "s a", "s i", "ster"},
	"area contains many totems": {"ains", "area", "ems", "ont", "rea", "s m", "s ma"},
	"area contains two unique bosses": {"ains", "area", "iq", "ont", "rea", "s t", "ses", "sses", "tw", "ue"},
	"area has increased monster variety": {"a h", "area", "ase", "ased", "cre", "d mo", "eas", "ed mo", "ety", "has", "mon", "nst", "rea", "s i", "s in", "sed m", "ster"},
	"area has patches of burning ground": {"a h", "area", "as p", "atc", "es o", "f b", "has", "ning", "rea", "s o", "s of", "s p", "tc"},
	"area has patches of chilled ground": {"a h", "area", "as p", "atc", "d gr", "es o", "f c", "has", "hil", "rea", "s o", "s of", "s of c", "s p", "tc"},
	"area has patches of desecrated ground": {"a h", "area", "as p", "atc", "d gr", "es o", "f d", "has", "rea", "s o", "s of", "s p", "sec", "tc"},
	"area has patches of shocked ground which increase damage taken by #%": {"%", "a h", "ama", "area", "as p", "ase", "atc", "by", "cre", "d gr", "d w", "e d", "e ta", "eas", "es o", "f s", "has", "rea", "s o", "s of", "s p", "tak", "tc"},
	"area is inhabited by # additional rogue exile": {"add", "area", "by", "d b", "d by", "e e", "gu", "ite", "iti", "nh", "rea", "s i", "s in", "ue"},
	"area is inhabited by # additional rogue exiles": {"add", "area", "by", "d b", "d by", "e e", "gu", "iles", "ite", "iti", "les", "nh", "rea", "s i", "s in", "ue", "xiles"},
	"area is inhabited by # additional rogue exiles§area is inhabited by # additional rogue exile": {"iles", "les", "xiles"},
	"area is inhabited by abominations": {"area", "bom", "by", "by a", "d b", "d by", "ite", "nh", "rea", "s i", "s in", "y a"},
	"area is inhabited by animals": {"als", "ani", "area", "by", "by a", "d b", "d by", "ite", "nh", "rea", "s i", "s in", "y a", "y an"},
	"area is inhabited by cultists of kitava": {"area", "by", "cul", "d b", "d by", "ist", "ite", "nh", "rea", "s i", "s in", "s o", "s of", "sts", "ts o", "y c"},
	"area is inhabited by demons": {"area", "by", "d b", "d by", "emo", "ite", "mon", "nh", "rea", "s i", "s in"},
	"area is inhabited by ghosts": {"area", "by", "d b", "d by", "gho", "ite", "nh", "rea", "s i", "s in", "sts", "y g"},
	"area is inhabited by goatmen": {"area", "by", "d b", "d by", "ite", "nh", "oa", "rea", "s i", "s in", "y g"},
	"area is inhabited by humanoids": {"area", "by", "d b", "d by", "hum", "ite", "nh", "oi", "oid", "rea", "s i", "s in"},
	"area is inhabited by lunaris fanatics": {"ana", "area", "by", "cs", "d b", "d by", "ite", "lu", "lun", "nh", "rea", "s f", "s i", "s in", "tic"},
	"area is inhabited by ranged monsters": {"ang", "area", "by", "d b", "d by", "d mo", "d monsters", "ed mo", "ite", "mon", "nh", "nst", "rea", "s i", "s in", "ster", "ters", "y r"},
	"area is inhabited by sea witches and their spawn": {"area", "aw", "by", "by s", "d b", "d by", "es a", "ite", "nh", "rea", "s a", "s an", "s i", "s in", "tc", "wi"},
	"area is inhabited by skeletons": {"area", "by", "by s", "d b", "d by", "ele", "eto", "ite", "nh", "rea", "s i", "s in", "sk"},
	"area is inhabited by solaris fanatics": {"ana", "area", "by", "by s", "cs", "d b", "d by", "ite", "lar", "nh", "rea", "s f", "s i", "s in", "tic"},
	"area is inhabited by undead": {"area", "by", "d b", "d by", "dea", "ite", "nh", "rea", "s i", "s in", "y u"},
	"areas have patches of consecrated ground": {"area", "as h", "atc", "d gr", "eas", "es o", "f c", "hav", "rea", "s h", "s ha", "s hav", "s o", "s of", "s of c", "sec", "tc"},
	"buffs on players expire #% faster": {"%", "% f", "ff", "fs", "ire", "lay", "rs e", "s ex", "s o", "s on", "ster", "xp", "ye", "yers"},
	"buffs on players expire #% slower": {"%", "% s", "ff", "fs", "ire", "lay", "rs e", "s ex", "s o", "s on", "xp", "ye", "yers"},
	"cannot leech from monsters": {"ech", "from", "lee", "mon", "nno", "nst", "ster", "ters"},
	"magic monster packs each have a bloodline mod": {"ack", "acks", "dl", "e a", "e mo", "e mod", "gi", "h h", "hav", "mod", "mon", "nst", "r p", "ster", "ve a"},
	"monsters are hexproof": {"hex", "mon", "nst", "rs a", "rs ar", "s a", "s ar", "s are", "ster", "ters", "xp"},
	"monsters blind on hit": {"bli", "hit", "ind", "mon", "n h", "nst", "s b", "ster", "ters"},
	"monsters cannot be affected by elemental ailments": {"af", "by", "d b", "d by", "e a", "ect", "ele", "emen", "fec", "ff", "lem", "lm", "mon", "nno", "nst", "rs c", "s c", "ster", "t b", "ters", "ters c"},
	"monsters cannot be stunned": {"e s", "mon", "nno", "nst", "rs c", "s c", "ster", "t b", "ters", "ters c"},
	"monsters cannot be taunted": {"be t", "e ta", "mon", "nno", "nst", "rs c", "s c", "ster", "t b", "ters", "ters c"},
	"monsters deal #% extra physical damage as cold": {"%", "% e", "a p", "al d", "ama", "as c", "dea", "e a", "e as", "eal", "hys", "l d", "mon", "nst", "s c", "s co", "s d", "ster", "ters", "xt"},
	"monsters deal #% extra physical damage as fire": {"%", "% e", "a p", "al d", "ama", "as f", "as fi", "dea", "e a", "e as", "eal", "fir", "hys", "ire", "l d", "mon", "nst", "s d", "s f", "ster", "ters", "xt"},
	"monsters deal #% extra physical damage as lightning": {"%", "% e", "a p", "al d", "ama", "dea", "e a", "e as", "eal", "hys", "l d", "mon", "ning", "nst", "s d", "ster", "ters", "tn", "xt"},
	"monsters fire # additional projectiles": {"add", "cti", "ect", "fir", "iles", "ire", "iti", "je", "les", "mon", "nst", "rs f", "s f", "ster", "ters"},
	"monsters gain #% of maximum life as extra maximum energy shield": {"%", "% o", "a m", "ax", "e a", "e as", "ene", "fe a", "gai", "gy", "if", "ife", "mon", "nst", "s ex", "s g", "ster", "ters", "ters g", "xt"},
	"monsters gain a frenzy charge on hit": {"a f", "arg", "gai", "hit", "mon", "n a", "n h", "nst", "nz", "s g", "s gain a", "s gain a f", "ster", "ters", "ters g", "y c"},
	"monsters gain a power charge on hit": {"a p", "a po", "arg", "gai", "hit", "mon", "n a", "n h", "nst", "pow", "r c", "r ch", "s g", "s gain a", "s gain a p", "ster", "ters", "ters g"},
	"monsters gain an endurance charge on hit": {"ance", "arg", "dur", "e cha", "gai", "hit", "mon", "n a", "n e", "n h", "nst", "s g", "s gain a", "s gain an", "ster", "ters", "ters g", "ura"},
	"monsters have #% chance to avoid elemental ailments": {"%", "% c", "ance", "avo", "ce t", "d e", "d el", "e to", "e to a", "ele", "emen", "hanc", "hav", "lem", "lm", "mon", "nst", "o a", "oi", "oid", "rs h", "rs ha", "s h", "s ha", "s hav", "ster", "ters", "ters h", "ters ha"},
	"monsters have #% chance to blind on hit": {"%", "% c", "ance", "bli", "ce t", "e to", "hanc", "hav", "hit", "ind", "mon", "n h", "nst", "o b", "o bl", "o bli", "rs h", "rs ha", "s h", "s ha", "s hav", "ster", "ters", "ters h", "ters ha"},
	"monsters have #% chance to gain a frenzy charge on hit": {"%", "% c", "a f", "ance", "arg", "ce t", "e to", "gai", "hanc", "hav", "hit", "mon", "n a", "n h", "nst", "nz", "o g", "o gain a f", "rs h", "rs ha", "s h", "s ha", "s hav", "ster", "ters", "ters h", "ters ha", "y c"},
	"monsters have #% chance to gain a power charge on hit": {"%", "% c", "a p", "a po", "ance", "arg", "ce t", "e to", "gai", "hanc", "hav", "hit", "mon", "n a", "n h", "nst", "o g", "o gain a p", "pow", "r c", "r ch", "rs h", "rs ha", "s h", "s ha", "s hav", "ster", "ters", "ters h", "ters ha"},
	"monsters have #% chance to gain an endurance charge on hit": {"%", "% c", "ance", "arg", "ce t", "dur", "e cha", "e to", "gai", "hanc", "hav", "hit", "mon", "n a", "n e", "n h", "nst", "o g", "o gain an", "rs h", "rs ha", "s h", "s ha", "s hav", "ster", "ters", "ters h", "ters ha", "ura"},
	"monsters have #% chance to hinder on hit with spells": {"%", "% c", "ance", "ce t", "e to", "h s", "hanc", "hav", "hit", "ind", "ith", "mon", "n h", "nst", "o h", "pel", "rs h", "rs ha", "s h", "s ha", "s hav", "spe", "ster", "t w", "ters", "ters h", "ters ha", "wi"},
	"monsters have #% chance to impale with attacks": {"%", "% c", "ack", "acks", "ale", "ance", "att", "ce t", "e to", "e w", "h a", "hanc", "hav", "ith", "mon", "nst", "o i", "rs h", "rs ha", "s h", "s ha", "s hav", "ster", "tac", "ters", "ters h", "ters ha", "wi"},
	"monsters have #% chance to maim on hit with attacks": {"%", "% c", "ack", "acks", "aim", "ance", "att", "ce t", "e to", "h a", "hanc", "hav", "hit", "ith", "mon", "n h", "nst", "o m", "rs h", "rs ha", "s h", "s ha", "s hav", "ster", "t w", "tac", "ters", "ters h", "ters ha", "wi"},
	"monsters have #% chance to steal power, frenzy and endurance charges on hit": {"%", "% c", ",", "ance", "arg", "ce t", "d e", "d en", "dur", "e cha", "e to", "eal", "es o", "es on", "ges", "hanc", "hav", "hit", "mon", "n h", "nst", "nz", "o s", "o st", "pow", "r,", "rs h", "rs ha", "s h", "s ha", "s hav", "s o", "s on", "s on h", "ster", "ters", "ters h", "ters ha", "ura", "y a", "y an"},
	"monsters have #% chance to suppress spell damage": {"%", "% c", "ama", "ance", "ce t", "e to", "ess", "hanc", "hav", "l d", "mon", "nst", "o s", "o su", "pel", "pp", "rs h", "rs ha", "s h", "s ha", "s hav", "s s", "spe", "ster", "ters", "ters h", "ters ha"},
	"monsters have #% increased accuracy rating": {"%", "% i", "ase", "ased", "cc", "cre", "d a", "d ac", "eas", "hav", "mon", "nst", "rea", "rs h", "rs ha", "s h", "s ha", "s hav", "ster", "ters", "ters h", "ters ha", "ura", "y r", "y rat"},
	"monsters have #% increased area of effect": {"%", "% i", "a o", "a of", "area", "ase", "ased", "cre", "d a", "d ar", "eas", "ect", "eff", "f e", "fec", "ff", "hav", "mon", "nst", "rea", "rs h", "rs ha", "s h", "s ha", "s hav", "ster", "ters", "ters h", "ters ha"},
	"monsters have #% increased critical strike chance": {"%", "% i", "ance", "ase", "ased", "cre", "e cha", "eas", "hanc", "hav", "ik", "iti", "ke c", "mon", "nst", "rea", "rs h", "rs ha", "s h", "s ha", "s hav", "ster", "ters", "ters h", "ters ha", "tic"},
	"monsters have a #% chance to avoid poison, impale, and bleeding": {"%", "% c", ",", "ale", "ance", "avo", "ce t", "d b", "e a", "e to", "e to a", "e,", "eed", "hanc", "hav", "iso", "lee", "mon", "n,", "nst", "o a", "oi", "oid", "rs h", "rs ha", "s h", "s ha", "s hav", "s have a", "ster", "ters", "ters h", "ters ha", "ve a"},
	"monsters have a #% chance to cause elemental ailments on hit": {"%", "% c", "ance", "cau", "ce t", "e a", "e e", "e to", "ele", "emen", "hanc", "hav", "hit", "lem", "lm", "mon", "n h", "nst", "rs h", "rs ha", "s h", "s ha", "s hav", "s have a", "s o", "s on", "s on h", "ster", "ters", "ters h", "ters ha", "ts o", "ve a"},
	"monsters hinder on hit with spells": {"h s", "hit", "ind", "ith", "mon", "n h", "nst", "pel", "rs h", "s h", "s hi", "spe", "ster", "t w", "ters", "ters h", "wi"},
	"monsters inflict impale with attacks": {"ack", "acks", "ale", "att", "ct i", "e w", "fli", "h a", "ith", "mon", "nst", "s i", "s in", "ster", "tac", "ters", "wi"},
	"monsters maim on hit with attacks": {"ack", "acks", "aim", "att", "h a", "hit", "ith", "mon", "n h", "nst", "rs m", "s m", "s ma", "ster", "t w", "tac", "ters", "wi"},
	"monsters poison on hit": {"hit", "iso", "mon", "n h", "n o", "nst", "oi", "s p", "ster", "ters"},
	"monsters reflect #% of elemental damage": {"%", "% o", "al d", "ama", "ect", "efl", "ele", "emen", "f e", "f el", "l d", "lem", "mon", "nst", "ster", "ters"},
	"monsters reflect #% of physical damage": {"%", "% o", "al d", "ama", "ect", "efl", "f p", "hys", "l d", "mon", "nst", "ster", "ters"},
	"monsters steal power, frenzy and endurance charges on hit": {",", "ance", "arg", "d e", "d en", "dur", "e cha", "eal", "es o", "es on", "ges", "hit", "mon", "n h", "nst", "nz", "pow", "r,", "rs s", "s o", "s on", "s on h", "s s", "ster", "ters", "ura", "y a", "y an"},
	"monsters take #% reduced extra damage from critical strikes": {"%", "% r", "a d", "ama", "ced e", "d e", "e f", "ed e", "from", "ik", "iti", "mon", "nst", "s t", "ster", "tak", "ters", "tic", "uc", "xt"},
	"monsters' action speed cannot be modified to below base value": {"' a", "ase", "cti", "ctio", "e mo", "e mod", "eed", "if", "lu", "mod", "mon", "nno", "nst", "o b", "pee", "s'", "spe", "ster", "t b", "ters", "ue"},
	"monsters' skills chain # additional times": {"' s", "add", "chai", "iti", "kil", "mon", "nst", "s c", "s'", "sk", "ster", "ters"},
	"players and monsters fire # additional projectiles": {"add", "cti", "d mo", "d monsters", "ect", "fir", "iles", "ire", "iti", "je", "lay", "les", "mon", "nd m", "nst", "rs a", "rs f", "s a", "s an", "s f", "ster", "ters", "ye", "yers", "yers a"},
	"players and monsters fire # additional projectiles§monsters fire # additional projectiles": {"d mo", "d monsters", "lay", "nd m", "rs a", "s a", "s an", "ye", "yers", "yers a"},
	"players are cursed with elemental weakness": {"d w", "d wi", "ele", "emen", "ess", "h e", "ith", "kn", "lay", "lem", "re c", "rs a", "rs ar", "s a", "s ar", "s are", "wi", "ye", "yers", "yers a"},
	"players are cursed with enfeeble": {"d w", "d wi", "ebl", "h e", "ith", "lay", "re c", "rs a", "rs ar", "s a", "s ar", "s are", "wi", "ye", "yers", "yers a"},
	"players are cursed with temporal chains": {"ains", "chai", "d w", "d wi", "h t", "ith", "lay", "re c", "rs a", "rs ar", "s a", "s ar", "s are", "wi", "ye", "yers", "yers a"},
	"players are cursed with vulnerability": {"d w", "d wi", "ith", "lay", "ln", "re c", "rs a", "rs ar", "s a", "s ar", "s are", "wi", "ye", "yers", "yers a"},
	"players cannot inflict exposure": {"fli", "lay", "nno", "osu", "pos", "rs c", "s c", "xp", "ye", "yers", "yers c"},
	"players cannot regenerate life, mana or energy shield": {",", ", m", "a o", "ana", "e,", "ene", "gy", "if", "ife", "lay", "nno", "r e", "rs c", "s c", "ye", "yers", "yers c"},
	"players gain #% reduced flask charges": {"%", "% r", "arg", "ask", "gai", "ges", "lay", "s g", "sk", "uc", "ye", "yers"},
	"players have #% increased effect of non-curse auras from skills": {"%", "% i", "-", "as f", "ase", "ased", "cre", "ct o", "d e", "e a", "eas", "ect", "ed e", "eff", "fec", "ff", "from", "hav", "kil", "lay", "rea", "rs h", "rs ha", "s f", "s fr", "s h", "s ha", "s hav", "sed e", "sk", "ura", "ye", "yers", "yers h"},
	"players have #% less accuracy rating": {"%", "% l", "cc", "ess", "hav", "lay", "les", "rs h", "rs ha", "s a", "s ac", "s h", "s ha", "s hav", "ss a", "ura", "y r", "y rat", "ye", "yers", "yers h"},
	"players have #% less area of effect": {"%", "% l", "a o", "a of", "area", "ect", "eff", "ess", "f e", "fec", "ff", "hav", "lay", "les", "rea", "rs h", "rs ha", "s a", "s ar", "s are", "s area", "s h", "s ha", "s hav", "ss a", "ss ar", "ye", "yers", "yers h"},
	"players have #% less armour": {"%", "% l", "ess", "hav", "lay", "les", "rs h", "rs ha", "s a", "s ar", "s arm", "s h", "s ha", "s hav", "ss a", "ss ar", "ye", "yers", "yers h"},
	"players have #% less cooldown recovery rate": {"%", "% l", "coo", "ecov", "ess", "hav", "lay", "les", "rs h", "rs ha", "s c", "s co", "s h", "s ha", "s hav", "ss c", "y r", "y rat", "ye", "yers", "yers h"},
	"players have #% less recovery rate of life and energy shield": {"%", "% l", "d e", "d en", "e a", "ecov", "ene", "ess", "f l", "fe a", "gy", "hav", "if", "ife", "lay", "les", "rs h", "rs ha", "s h", "s ha", "s hav", "y r", "y rat", "ye", "yers", "yers h"},
	"players have #% more accuracy rating": {"%", "% m", "% mo", "cc", "e a", "e ac", "hav", "lay", "more", "rs h", "rs ha", "s h", "s ha", "s hav", "ura", "y r", "y rat", "ye", "yers", "yers h"},
	"players have #% more cooldown recovery rate": {"%", "% m", "% mo", "coo", "e co", "ecov", "hav", "lay", "more", "re c", "rs h", "rs ha", "s h", "s ha", "s hav", "y r", "y rat", "ye", "yers", "yers h"},
	"players have #% reduced chance to block": {"%", "% r", "ance", "ce t", "d ch", "e to", "hanc", "hav", "lay", "o b", "o bl", "rs h", "rs ha", "s h", "s ha", "s hav", "uc", "ye", "yers", "yers h"},
	"players have #% reduced effect of non-curse auras from skills": {"%", "% r", "-", "as f", "ced e", "ced ef", "ct o", "d e", "e a", "ect", "ed e", "eff", "fec", "ff", "from", "hav", "kil", "lay", "rs h", "rs ha", "s f", "s fr", "s h", "s ha", "s hav", "sk", "uc", "ura", "ye", "yers", "yers h"},
	"players have #% to amount of suppressed spell damage prevented": {"%", "ama", "ess", "esse", "ev", "f s", "hav", "l d", "lay", "o a", "pel", "pp", "rs h", "rs ha", "s h", "s ha", "s hav", "spe", "ye", "yers", "yers h"},
	"rare monsters each have a nemesis mod": {"a n", "e a", "e mo", "e mon", "h h", "hav", "mod", "mon", "nem", "nst", "rar", "re m", "rs e", "s m", "s mo", "sis", "ster", "ters", "ve a"},
	"slaying enemies close together attracts monsters from beyond": {"att", "cl", "cts", "e to", "ene", "from", "lay", "mon", "nem", "nst", "r a", "rs f", "s c", "s f", "s fr", "s m", "s mo", "ster", "ters"},
	"slaying enemies close together has a #% chance to attract monsters from beyond": {"%", "% c", "ance", "att", "ce t", "cl", "e to", "e to a", "ene", "from", "hanc", "has", "lay", "mon", "nem", "nst", "o a", "r h", "rs f", "s a", "s c", "s f", "s fr", "ster", "ters"},
	"unique boss deals #% increased damage": {"%", "% i", "als", "ama", "ase", "ased", "cre", "d d", "dea", "eal", "eas", "iq", "rea", "s d", "ue"},
	"unique boss has #% increased area of effect": {"%", "% i", "a o", "a of", "area", "ase", "ased", "cre", "d a", "d ar", "eas", "ect", "eff", "f e", "fec", "ff", "has", "iq", "rea", "s h", "s ha", "ss h", "ue"},
	"unique boss has #% increased attack and cast speed": {"%", "% i", "ack", "ase", "ased", "att", "cre", "d a", "eas", "eed", "has", "iq", "k a", "pee", "rea", "s h", "s ha", "spe", "ss h", "st s", "t spe", "tac", "ue"},
	"unique boss has #% increased life": {"%", "% i", "ase", "ased", "cre", "d li", "eas", "has", "if", "ife", "iq", "rea", "s h", "s ha", "ss h", "ue"},
	"unique bosses are possessed": {"es a", "ess", "esse", "iq", "pos", "poss", "s a", "s ar", "s are", "ses", "sses", "ue"},
}